apply plugin: "java"

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

compileJava.options.encoding = "UTF-8"

version = "2.1.4"

ext {
    mindustryVersion = 'v159.7'
    arcVersion = 'v159.7'
}

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.Arc:arc-core:$arcVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
    annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
}

allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs.addAll(['--release', '8'])
    }
}

jar {
    archiveFileName = "TsunamiMod.jar"
    from("assets")
}

task deploy(type: Jar) {
    dependsOn(configurations.runtimeClasspath)
    archiveFileName = "TsunamiMod.jar"
    from(sourceSets.main.output)
    from("assets")
    from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }) {
        exclude "META-INF/*"
    }
}
